### ISSUE TITLE
反编译后的作品无法正常打开

### ISSUE THREAD

**Issue by qzm4228** [Codemao-Hacker/CodemaoNemoDecompiler#1]
![Screenshot_2024-06-01-11-58-47-902_com.codemao.nemo.jpg](https://github.com/Codemao-Hacker/CodemaoNemoDecompiler/assets/150357059/721e50f0-d145-445b-a502-72da3dc55ba5)

**Comment by qzm4228** [comment]
这个貌似只能打开自己的作品，反编译别人的打不开

**Comment by MoonLeeeaf** [comment]
> 这个貌似只能打开自己的作品，反编译别人的打不开

@qzm4228  能给个样板么，或者workid，我去试一下

**Comment by qzm4228** [comment]
> > 这个貌似只能打开自己的作品，反编译别人的打不开
> 
> @qzm4228  能给个样板么，或者workid，把详细的流程给我，我去试一下
> 我已经反出几次了都正常，可以看一下是不是缺少什么文件，有时候可能缺个图片就打不开了（另外反编译过程中可能会出现一些网络问题，这种情况可以重试下）

>用户编号4169823
作品132679228

**Comment by qzm4228** [comment]
@MoonLeeeaf 等一下，前面那个id不会是要输入自己的吧

**Comment by qzm4228** [comment]
> > 这个貌似只能打开自己的作品，反编译别人的打不开
> 
> @qzm4228  能给个样板么，或者workid，把详细的流程给我，我去试一下
> 我已经反出几次了都正常，可以看一下是不是缺少什么文件，有时候可能缺个图片就打不开了（另外反编译过程中可能会出现一些网络问题，这种情况可以重试下）

导入后就这样了
![Screenshot_2024-06-01-13-24-08-191_com.codemao.nemo.jpg](https://github.com/Codemao-Hacker/CodemaoNemoDecompiler/assets/150357059/75703227-66ff-4fe1-9fad-f64d8bf688c4)

**Comment by MoonLeeeaf** [comment]
> @MoonLeeeaf 等一下，前面那个id不会是要输入自己的吧

@qzm4228 肯定的，用户编号输入自己的，workid随意，然后把文件移动进去就行了

**Comment by qzm4228** [comment]
> > @MoonLeeeaf 等一下，前面那个id不会是要输入自己的吧
> 
> @qzm4228 肯定的，用户编号输入自己的，workid随意，然后把文件移动进去就行了

可是导入后就这样了
![Screenshot_2024-06-01-13-24-08-191_com.codemao.nemo.jpg](https://github.com/Codemao-Hacker/CodemaoNemoDecompiler/assets/150357059/2f4bff6e-9a98-4436-af1a-2f1a9ac72d4b)

**Comment by MoonLeeeaf** [comment]
等我测试下

**Comment by MoonLeeeaf** [comment]
我这边能正常打开，要不你测试下
我移动端网页有点问题，用的电脑反出来的
文件传不上去，见谅（

**Comment by MoonLeeeaf** [comment]
![Screenshot_2024-06-01-13-48-46-879_com codemao nemo](https://github.com/Codemao-Hacker/CodemaoNemoDecompiler/assets/150461955/8a730a67-ae05-4fcc-924f-4f8841bb46dd)

**Comment by MoonLeeeaf** [comment]
> > > @MoonLeeeaf 等一下，前面那个id不会是要输入自己的吧
> > 
> > 
> > @qzm4228 肯定的，用户编号输入自己的，workid随意，然后把文件移动进去就行了
> 
> @MoonLeeeaf 可是导入后就这样了 ![Screenshot_2024-06-01-13-24-08-191_com.codemao.nemo.jpg](https://private-user-images.githubusercontent.com/150357059/335780029-2f4bff6e-9a98-4436-af1a-2f1a9ac72d4b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMjEyOTQsIm5iZiI6MTcxNzIyMDk5NCwicGF0aCI6Ii8xNTAzNTcwNTkvMzM1NzgwMDI5LTJmNGJmZjZlLTlhOTgtNDQzNi1hZjFhLTJmMWE5YWM3MmQ0Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwNTQ5NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTYyYTA5M2JhNDI1OWM3N2VkYmQwODFmNjAyMzg0NzE4ZTIwOTExZjVkYWNkY2FjOWFhNDMzNWRmMGVlZmM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LN38t3E3Ttnl75N4unmS22WUgMgvV2R2Mx6_W8AWIWE)

录个过程我看看？有点玄乎

**Comment by qzm4228** [comment]
> > > > @MoonLeeeaf 等一下，前面那个id不会是要输入自己的吧
> > > 
> > > 
> > > @qzm4228 肯定的，用户编号输入自己的，workid随意，然后把文件移动进去就行了
> > 
> > @MoonLeeeaf 可是导入后就这样了 ![Screenshot_2024-06-01-13-24-08-191_com.codemao.nemo.jpg](https://private-user-images.githubusercontent.com/150357059/335780029-2f4bff6e-9a98-4436-af1a-2f1a9ac72d4b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMjEyOTQsIm5iZiI6MTcxNzIyMDk5NCwicGF0aCI6Ii8xNTAzNTcwNTkvMzM1NzgwMDI5LTJmNGJmZjZlLTlhOTgtNDQzNi1hZjFhLTJmMWE5YWM3MmQ0Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwNTQ5NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTYyYTA5M2JhNDI1OWM3N2VkYmQwODFmNjAyMzg0NzE4ZTIwOTExZjVkYWNkY2FjOWFhNDMzNWRmMGVlZmM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LN38t3E3Ttnl75N4unmS22WUgMgvV2R2Mx6_W8AWIWE)
> 
> 录个过程我看看？有点玄乎

视频在这，改个mp4后缀能看
https://www.123pan.com/s/Dc7jVv-R53l3.html

**Comment by MoonLeeeaf** [comment]
@qzm4228 Nemo版本迭代导致了文件结构不同, 我这边测试版本是 4.5.0 和 4.3.4, 难怪有人说作品全丢了
你可以逝世降级, 或者新建空白作品, 把 nemo_users_db 打成压缩包发给我分析一下

**Comment by qzm4228** [comment]
> @qzm4228 Nemo版本迭代导致了文件结构不同, 我这边测试版本是 4.5.0 和 4.3.4, 难怪有人说作品全丢了
> 你可以逝世降级, 或者新建空白作品, 把 nemo_users_db 打成压缩包发给我分析一下
> 这种情况下我只能重新分析, 见谅

我试试降级，我现版本如果将编译后的作品放进去就会导致进去一片白，删掉就没事了

**Comment by MoonLeeeaf** [comment]
@qzm4228 能打开了么

**Comment by qzm4228** [comment]
> @qzm4228 能打开了么

@MoonLeeeaf 不能qwq，降级也不行（远古版都不行
![Screenshot_2024-06-01-14-57-02-369_com.miui.securitycenter.jpg](https://github.com/Codemao-Hacker/CodemaoNemoDecompiler/assets/150357059/d3160302-2eae-4d96-8cb4-a045244bd2db)

**Comment by MoonLeeeaf** [comment]
> > @qzm4228 能打开了么
> 
> @MoonLeeeaf 不能qwq，降级也不行，降了级也是一片白（远古版都不行 ![Screenshot_2024-06-01-14-57-02-369_com.miui.securitycenter.jpg](https://private-user-images.githubusercontent.com/150357059/335783843-d3160302-2eae-4d96-8cb4-a045244bd2db.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMjU3NjUsIm5iZiI6MTcxNzIyNTQ2NSwicGF0aCI6Ii8xNTAzNTcwNTkvMzM1NzgzODQzLWQzMTYwMzAyLTJlYWUtNGQ5Ni04Y2I0LWEwNDUyNDRiZDJkYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwNzA0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzEwZmJhOGY0YjVlYTJlYTNhNjk4YTYwNjA2NGJkODFlNjdjNjhkMzU0MjNjZmZiMjI1ZDg3Mzc5NzRhNWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qe1mGSTjFLf0Ryw9c7KT65ocdmHDKD2LEXkDjtUo6dY) ![Screenshot_2024-06-01-13-24-08-191_com.codemao.nemo.jpg](https://private-user-images.githubusercontent.com/150357059/335783897-f59d13d9-c67d-4a70-88e4-3af534c71e7f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMjU3NjUsIm5iZiI6MTcxNzIyNTQ2NSwicGF0aCI6Ii8xNTAzNTcwNTkvMzM1NzgzODk3LWY1OWQxM2Q5LWM2N2QtNGE3MC04OGU0LTNhZjUzNGM3MWU3Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwNzA0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODI5MDZlY2NlY2NkMzA5NGFjMGJmZWJkYjRiYjU2OTEwMDI0ZjQxOGUzMDUwNjA3YTQ1NDZhY2MzZjIyOWU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YkaZC_gd6Om8BZ8nKLITDvd2Dv_GLUvkwnz6vahfOXA)

@qzm4228 能麻烦你再录一下视频吗QWQ 我要晕了

**Comment by MoonLeeeaf** [comment]
有点累, 我今晚再来看看吧
另外你可以翻阅 nemo_users_db 和 <训练师编号> 文件夹, 看看有没有什么规律, 找一下共同点

**Comment by qzm4228** [comment]
> @qzm4228 能麻烦你截图 nemo_users_db 目录 以及子目录么QWQ, 我脑壳要晕力(悲

@MoonLeeeaf 也有可能是我操作方式有问题，你能录个视频吗

**Comment by qzm4228** [comment]
> @qzm4228 能麻烦你截图 nemo_users_db 目录 以及子目录么QWQ, 我脑壳要晕力(悲

https://github.com/Codemao-Hacker/CodemaoNemoDecompiler/assets/150357059/0119e4c6-1e96-4c9f-92c4-93e3fa58af24

**Comment by MoonLeeeaf** [comment]
你那个视频不知道为什么放不出来
这好玄学啊（
https://github.com/Codemao-Hacker/CodemaoNemoDecompiler/assets/150461955/0fdddaab-d2e0-41d4-a0dd-1a1702525fee

**Comment by qzm4228** [comment]
> @qzm4228 视频不知道为什么放不出来
> 这好玄学啊（
> 
> https://github.com/Codemao-Hacker/CodemaoNemoDecompiler/assets/150461955/2c7d6c35-015e-4eb6-8b2f-7585963911fe
> 
> 
> 我的正常，要不你先搜索下以你的训练师编号为名称的文件夹？
> 

@MoonLeeeaf 为啥啊，我跟你的操作一样啊

**Comment by MoonLeeeaf** [comment]
__

> > @qzm4228 视频不知道为什么放不出来
> > 这好玄学啊（
> > 
> >   
> >     
> >     
> > 
> >     2024_06_02_09_46_56.mp4
> >     
> >   
> > 
> >   
> > 
> >   
> > 
> > 
> > 我的正常，要不你先搜索下以你的训练师编号为名称的文件夹？
> 
> @MoonLeeeaf 为啥啊，我跟你的操作一样啊

@qzm4228 好玄学，我也不知道（

**Comment by qzm4228** [comment]
> __
> 
> > > @qzm4228 视频不知道为什么放不出来
> > > 这好玄学啊（
> > > 
> > >   
> > >     
> > >     
> > > 
> > >     2024_06_02_09_46_56.mp4
> > >     
> > >   
> > > 
> > >   
> > > 
> > >   
> > > 
> > > 
> > > 我的正常，要不你先搜索下以你的训练师编号为名称的文件夹？
> > 
> > @MoonLeeeaf 为啥啊，我跟你的操作一样啊
> 
> @qzm4228 好玄学，我也不知道（

@MoonLeeeaf 难道要断网吗？

**Comment by MoonLeeeaf** [comment]
> > __
> > > > @qzm4228 视频不知道为什么放不出来
> > > > 这好玄学啊（
> > > > ```
> > > > 2024_06_02_09_46_56.mp4
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 我的正常，要不你先搜索下以你的训练师编号为名称的文件夹？
> > > 
> > > 
> > > @MoonLeeeaf 为啥啊，我跟你的操作一样啊
> > 
> > 
> > @qzm4228 好玄学，我也不知道（
> 
> @MoonLeeeaf 难道要断网吗？

@qzm4228  按道理是不需要的，不过移动文件后要重启点个猫

**Comment by qzm4228** [comment]
@MoonLeeeaf 那我操作没错啊

**Comment by MoonLeeeaf** [comment]
> @MoonLeeeaf 那我操作没错啊

ummmmmmmmmmmmmmmmmm你新建个作品然后找它的.bcm文件，发路径到这里

**Comment by qzm4228** [comment]
> > @MoonLeeeaf 那我操作没错啊
> 
> @qzm4228 ummmmmmmmmmmmmmmmmm你新建个作品然后找它的.bcm文件，发路径到这里

/data/data/com.codemao.nemo/files/nemo_users_db/6902335/user_works/132679228/

**Comment by MoonLeeeaf** [comment]
莫得问他，再检查下操作是否有误（摊

**Comment by qzm4228** [comment]
> 莫得问题，再检查下操作是否有误（摊

更新到新版本后就无上述问题

**Comment by MoonLeeeaf** [comment]
可能有个版本文件结构改了
我一直没有更新过，4.3.4和5.0.0
如果确认没问题的话可以Close了（摊

**Comment by qzm4228** [comment]
> 可能有个版本文件结构改了，后来改回来了
> 我一直没有更新过，就用过4.3.4和5.0.0
> 如果确认没问题的话可以Close了（摊

可以
